# Generated by Django 2.0 on 2017-12-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Note', '0002_auto_20171213_0341'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('note', 'file')},
        ),
        migrations.AlterUniqueTogether(
            name='fold',
            unique_together={('parent', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('fold', 'name')},
        ),
    ]
